language: node_js
node_js:
  - '10'
dist: trusty
sudo: required

script:
  - npm run build
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" > .npmrc
deploy:
  - provider: script
    script: npm run publish:staging
    on:
      all_branches: true
  - provider: script
    script: npm run publish:library
    on:
      tags: true
