language: node_js
node_js:
  - '10'
dist: trusty
sudo: required
addons:
  chrome: stable
  firefox: latest

cache: npm

script:
  - npm run build:libs
  - if [ "$TRAVIS_TAG" == "" ]; then npm run test; fi
  - if [ "$TRAVIS_TAG" == "" ]; then npm run lint; fi
  - if [ "$TRAVIS_TAG" == "" ]; then npm run sonar; fi
  - npm run build:angular-showcase
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" > ~/.npmrc
deploy:
  - provider: script
    script: npm run publish:library
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: npm run publish:staging
    skip_cleanup: true
    on:
      all_branches: true
      tags: false
