language: node_js
node_js:
  - '10'
dist: trusty
sudo: required
addons:
  chrome: stable
  firefox: latest

cache: npm

env:
  global:
    - NODE_OPTIONS=--max_old_space_size=7168
script:
  - if [ "$TRAVIS_TAG" == "" ]; then npm run lint; fi
  - npm run build:angular-core
  - npm run build:angular-icons
  - npm run build:angular-keycloak
  - npm run build:angular-business
  - npm run build:angular-public
  - if [ "$TRAVIS_TAG" == "" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then npm run test; fi
  - if [ "$TRAVIS_TAG" == "" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run test:pr; fi
  - npm run build:angular-showcase
  - if [ "$TRAVIS_TAG" == "" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run publish:staging; fi
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" > ~/.npmrc
deploy:
  - provider: script
    script: npm run publish:library
    skip_cleanup: true
    on:
      tags: true
