language: node_js
node_js:
  - '10'
dist: trusty
sudo: required

cache: npm

addons:
  browserstack:
    username: mwereader1
    access_key:
      secure: vevri1oAy6MYDc/8P5EPNZQzOon0SG0EFXhDrLBR7AT+1rNBn3bPZ0zHq6PaV4a3O8/iFl3+joLgxg0yDx8jhZXI05dpPuCABgDd4Ekn4AynwkL1YjTiW22VQqF1GBxPF5eX5LGYseN/1WID5s/EfRUUK40sPXp76RYrx35bgf6raAnA6swqB/22/icjMqk+kxQJnzQQA82ZO4AEH84Ewo0rF2atceah3aBDIbUvEy3eeEJ9F87JgaL5+BPLAQOdeudUWmj6MYGpRlUNaiYNNy4ViWCQAKpz2c2dHnvmJy1n+FpUCxF0bIsG8/rF08c0g+anAcSRJdzNzvBN50aRslDj5Uc4SGyBUl/0HULcPjDd8ET5MaEVYHcjQL6uTh4j3F7KipyitEFHhoM/ZEarQj8+5+VGDWdFS0vvJhczXZRLZNs1GLUvbwolJu1Ht49KOTFFXRsHCttaNx3bVd2IYT71Hjn47zxwd7CLW388a8i/p03vRZxziOzZYZcfSSQljKd2puR7uRHzYfcnZahkrmu3lYepRUWUYbkxza41hD1i9+ij3EII1xxW4IEpe9A2JVcAm2q6p+91E72FyFaC0QUnWPfuU3L48zndH/6nvSQ0ES244Cvu1yV/DMIEEuCWRxXhHtsb+zrCY4Iv1W0hKiOBrcKP0mT3uBQoZbR+3Y0=
    forcelocal: true

script:
  - npm run lint
  - npm run build
  - npm run test
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" > .npmrc
deploy:
  - provider: script
    script: npm run publish:library
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: npm run publish:staging
    skip_cleanup: true
    on:
      condition: $TRAVIS_PULL_REQUEST != "false"
      all_branches: true
