language: node_js
node_js:
  - '10'
dist: trusty
sudo: required

addons:
  browserstack:
    username: $BROWSERSTACK_USERNAME
    access_key: $BROWSERSTACK_ACCESS_KEY

script:
  - npm run lint
  - npm run build
  - npm run test
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" > .npmrc
deploy:
  - provider: script
    script: npm run publish:library
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: npm run publish:staging
    skip_cleanup: true
    on:
      condition: $TRAVIS_PULL_REQUEST != "false"
      all_branches: true
