name: Continuous Integration
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '**'
env:
  BAZEL_COMMAND: bazelisk

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: "Yarn: Get cache directory path"
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: "Yarn: Restore dependencies from cache"
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '**/tools/postinstall/apply-patches.js') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: "Yarn: Install dependencies"
      run: yarn install --frozen-lockfile --non-interactive

    - name: "Lint: Run tslint and bazel linter"
      run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: "Bazel: Copy bazel.rc to user home"
      run: cp ./.github/.bazelrc ~/
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: "Yarn: Get cache directory path"
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: "Yarn: Restore dependencies from cache"
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '**/tools/postinstall/apply-patches.js') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: "Yarn: Install dependencies"
      run: yarn install --frozen-lockfile --non-interactive

    - name: "Bazel: Restore remote cache"
      uses: actions/cache@v2
      with:
        path: ~/.bazel-cache/sbb-angular
        key: bazel-noop-${{ github.sha }}
        restore-keys: |
          bazel-merged-
    - name: "Bazel: Build"
      run: yarn -s build all
    - name: "Bazel: Compress artifacts"
      run: |
        cd ~/.bazel-cache
        tar -I zstd -cf bazel-cache.tar.zst sbb-angular
    - name: "Bazel: Upload cache artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: bazel-cache-artifact
        path: ~/.bazel-cache/bazel-cache.tar.zst
    - name: "Bazel: Remove artifacts archive"
      run: rm -rf ~/.bazel-cache

  packages:
    runs-on: ubuntu-latest
    steps:
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: "Bazel: Copy bazel.rc to user home"
      run: cp ./.github/.bazelrc ~/
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: "Yarn: Get cache directory path"
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: "Yarn: Restore dependencies from cache"
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '**/tools/postinstall/apply-patches.js') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: "Yarn: Install dependencies"
      run: yarn install --frozen-lockfile --non-interactive

    - name: "Bazel: Restore remote cache"
      uses: actions/cache@v2
      with:
        path: ~/.bazel-cache/sbb-angular
        key: bazel-packages-${{ github.sha }}
        restore-keys: |
          bazel-packages-
    - name: "Bazel: Build packages"
      run: yarn -s build packages
    - name: "Bazel: Clean bazel disk cache"
      run: yarn -s bazel:cache clean --maxSize 150MB

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: "Bazel: Copy bazel.rc to user home"
      run: cp ./.github/.bazelrc ~/
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: "Yarn: Get cache directory path"
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: "Yarn: Restore dependencies from cache"
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '**/tools/postinstall/apply-patches.js') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: "Yarn: Install dependencies"
      run: yarn install --frozen-lockfile --non-interactive

    - name: "Bazel: Download cache artifacts"
      uses: actions/download-artifact@v2
      with:
        name: bazel-cache-artifact
        path: ~/.bazel-cache/
    - name: "Bazel: Unpack artifacts"
      run: |
        cd ~/.bazel-cache/
        tar -I zstd -xf bazel-cache.tar.zst
        rm -f bazel-cache.tar.zst
    - name: "Bazel: Run local tests"
      run: bazelisk test src/... --build_tag_filters=-e2e --test_tag_filters=-e2e --build_tests_only
    - name: "Bazel: Compress artifacts"
      run: |
        cd ~/.bazel-cache
        tar -I zstd -cf bazel-cache-test.tar.zst sbb-angular
    - name: "Bazel: Upload cache artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: bazel-cache-test-artifact
        path: ~/.bazel-cache/bazel-cache-test.tar.zst

  showcase:
    needs: build
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: "Bazel: Copy bazel.rc to user home"
      run: cp ./.github/.bazelrc ~/
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: "Yarn: Get cache directory path"
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: "Yarn: Restore dependencies from cache"
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '**/tools/postinstall/apply-patches.js') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: "Yarn: Install dependencies"
      run: yarn install --frozen-lockfile --non-interactive

    - name: "Bazel: Download cache artifacts"
      uses: actions/download-artifact@v2
      with:
        name: bazel-cache-artifact
        path: ~/.bazel-cache/
    - name: "Bazel: Unpack artifacts"
      run: |
        cd ~/.bazel-cache/
        tar -I zstd -xf bazel-cache.tar.zst
        rm -f bazel-cache.tar.zst
    - name: "Bazel: Build showcase"
      run: yarn -s build showcase
    - name: "Bazel: Compress artifacts"
      run: |
        cd ~/.bazel-cache
        tar -I zstd -cf bazel-cache-showcase.tar.zst sbb-angular
    - name: "Bazel: Upload cache artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: bazel-cache-showcase-artifact
        path: ~/.bazel-cache/bazel-cache-showcase.tar.zst

    - name: "Deploy: Pack showcase"
      run: mv $(npm pack ./dist/releases/showcase | tail -n 1) sbb-esta-angular-showcase.tgz
    - name: "Deploy: Upload PR to staging"
      if: github.event_name == 'pull_request'
      run: |
        curl --url https://angular-staging.app.sbb.ch/$PR_NUMBER \
        -X POST --user sbb:ezUxDHgb6rAHTDU0HLHJ \
        -F "tarball=@sbb-esta-angular-showcase.tgz"
    - name: "Deploy: Upload master to staging"
      if: github.ref == 'refs/heads/master'
      run: |
        curl --url https://angular-staging.app.sbb.ch/master \
        -X POST --user sbb:ezUxDHgb6rAHTDU0HLHJ \
        -F "tarball=@sbb-esta-angular-showcase.tgz"

  showcase-merge:
    needs: build
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: "Bazel: Copy bazel.rc to user home"
      run: cp ./.github/.bazelrc ~/
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: "Yarn: Get cache directory path"
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: "Yarn: Restore dependencies from cache"
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '**/tools/postinstall/apply-patches.js') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: "Yarn: Install dependencies"
      run: yarn install --frozen-lockfile --non-interactive

    - name: "Bazel: Download cache artifacts"
      uses: actions/download-artifact@v2
      with:
        name: bazel-cache-artifact
        path: ~/.bazel-cache/
    - name: "Bazel: Unpack artifacts"
      run: |
        cd ~/.bazel-cache/
        tar -I zstd -xf bazel-cache.tar.zst
        rm -f bazel-cache.tar.zst
    - name: "Bazel: Build showcase"
      run: yarn -s build showcase-merge
    - name: "Bazel: Compress artifacts"
      run: |
        cd ~/.bazel-cache
        tar -I zstd -cf bazel-cache-showcase-merge.tar.zst sbb-angular
    - name: "Bazel: Upload cache artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: bazel-cache-showcase-merge-artifact
        path: ~/.bazel-cache/bazel-cache-showcase-merge.tar.zst

    - name: "Deploy: Pack showcase"
      run: mv $(npm pack ./dist/releases/showcase-merge | tail -n 1) sbb-esta-angular-showcase-merge.tgz
    - name: "Deploy: Upload PR to staging"
      if: github.event_name == 'pull_request'
      run: |
        curl --url https://angular-staging.app.sbb.ch/${PR_NUMBER}-merge \
        -X POST --user sbb:ezUxDHgb6rAHTDU0HLHJ \
        -F "tarball=@sbb-esta-angular-showcase-merge.tgz"
    - name: "Deploy: Upload master to staging"
      if: github.ref == 'refs/heads/master'
      run: |
        curl --url https://angular-staging.app.sbb.ch/master-merge \
        -X POST --user sbb:ezUxDHgb6rAHTDU0HLHJ \
        -F "tarball=@sbb-esta-angular-showcase-merge.tgz"

  merge-caches:
    needs: [test, showcase, showcase-merge]
    runs-on: ubuntu-latest
    steps:
    - name: "Bazel: Create cache directory"
      run: mkdir -p ~/.bazel-cache/
    - name: "Bazel: Restore remote cache"
      uses: actions/cache@v2
      with:
        path: ~/.bazel-cache/sbb-angular
        key: bazel-merged-${{ github.sha }}
        restore-keys: |
          bazel-merged-
    - name: "Bazel: Download test cache artifacts"
      uses: actions/download-artifact@v2
      with:
        name: bazel-cache-test-artifact
        path: ~/.bazel-cache/
    - name: "Bazel: Download showcase cache artifacts"
      uses: actions/download-artifact@v2
      with:
        name: bazel-cache-showcase-artifact
        path: ~/.bazel-cache/
    - name: "Bazel: Download showcase-merge cache artifacts"
      uses: actions/download-artifact@v2
      with:
        name: bazel-cache-showcase-merge-artifact
        path: ~/.bazel-cache/
    - name: "Bazel: Unpack artifacts"
      run: |
        cd ~/.bazel-cache/
        tar -I zstd -xf bazel-cache-test.tar.zst
        rm -f bazel-cache-test.tar.zst
        tar -I zstd -xf bazel-cache-showcase.tar.zst
        rm -f bazel-cache-showcase.tar.zst
        tar -I zstd -xf bazel-cache-showcase-merge.tar.zst
        rm -f bazel-cache-showcase-merge.tar.zst
    - name: "Bazel: Clean bazel disk cache"
      run: yarn -s bazel:cache clean --maxSize 500MB --individualMaxSize=20MB
