name: Continuous Integration
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '**'
env:
  BAZEL_COMMAND: bazelisk

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: "Yarn: Get cache directory path"
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: "Yarn: Restore dependencies from cache"
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '**/tools/postinstall/apply-patches.js') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: "Yarn: Install dependencies"
      run: yarn install --frozen-lockfile --non-interactive

    - name: "Lint: Run tslint and bazel linter"
      run: yarn lint

  build:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Copy bazel.rc to user home
      run: cp ./.github/.bazelrc ~/
    - name: "Bazel Cache: Apply configuration"
      if: github.event_name == 'push'
      run: |
        echo "build --config=remote-disk-caching" >> ~/.bazelrc
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: "Yarn: Get cache directory path"
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: "Yarn: Restore dependencies from cache"
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '**/tools/postinstall/apply-patches.js') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: "Yarn: Install dependencies"
      run: yarn install --frozen-lockfile --non-interactive
    - name: "Cache: Restore bazel disk cache"
      run: yarn -s bazel:cache restore build
    - name: "Build: Bazel"
      run: yarn -s build all
    - name: "Test: Run local tests"
      run: bazelisk test src/... --build_tag_filters=-e2e --test_tag_filters=-e2e --build_tests_only
    - name: "Build: Showcase"
      run: yarn -s build showcase
    - name: "Cache: Clean bazel disk cache"
      run: yarn -s bazel:cache clean --maxSize 300MB
    - name: "Cache: Save bazel disk cache"
      run: yarn -s bazel:cache save build
    - name: "Pack: Showcase"
      run: mv $(npm pack ./dist/releases/showcase | tail -n 1) sbb-esta-angular-showcase.tgz
    - name: "Deploy: Staging"
      if: github.event_name == 'pull_request'
      run: |
        curl --url https://angular-staging.app.sbb.ch/$PR_NUMBER \
        -X POST --user sbb:ezUxDHgb6rAHTDU0HLHJ \
        -F "tarball=@sbb-esta-angular-showcase.tgz"

  packages:
    runs-on: ubuntu-latest
    steps:
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Copy bazel.rc to user home
      run: cp ./.github/.bazelrc ~/
    - name: "Bazel Cache: Apply configuration"
      if: github.event_name == 'push'
      run: |
        echo "build --config=remote-http-caching" >> ~/.bazelrc
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: "Yarn: Get cache directory path"
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: "Yarn: Restore dependencies from cache"
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '**/tools/postinstall/apply-patches.js') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: "Yarn: Install dependencies"
      run: yarn install --frozen-lockfile --non-interactive
    - name: "Cache: Restore bazel disk cache"
      run: yarn -s bazel:cache restore packages
    - name: "Build: Packages"
      run: yarn -s build packages
    - name: "Cache: Clean bazel disk cache"
      run: yarn -s bazel:cache clean --maxSize 150MB
    - name: "Cache: Save bazel disk cache"
      run: yarn -s bazel:cache save packages
