name: Continuous Integration
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Copy bazel.rc to user home
      run: cp ./.github/.bazelrc ~/
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: "Yarn: Get cache directory path"
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: "Yarn: Restore dependencies from cache"
      uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-{{ hashFiles('**/tools/postinstall/apply-patches.js') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: "Yarn: Install dependencies"
      run: yarn install --frozen-lockfile --non-interactive

    - name: "Bazelisk: Restore dependencies from cache"
      uses: actions/cache@v1
      id: bazelisk-cache
      with:
        path: "~/.cache/bazelisk"
        key: ${{ runner.os }}-bazelisk-${{ hashFiles('**/WORKSPACE') }}-{{ hashFiles('**/.bazelversion') }}
        restore-keys: |
          ${{ runner.os }}-bazelisk-

    - name: "Bazel: Restore artifacts from cache"
      uses: actions/cache@v1
      id: bazel-cache
      with:
        path: "~/bazel_repository_cache"
        key: ${{ runner.os }}-bazel-${{ hashFiles('**/WORKSPACE') }}-{{ hashFiles('**/.bazelversion') }}
        restore-keys: |
          ${{ runner.os }}-bazel-

    - name: "Build: Migrate public to business components"
      run: yarn -s build:business:public2business
    - name: "Build: Bazel Core"
      run: bazelisk build src/core/... --build_tag_filters=-docs-package,-release-package
    - name: "Build: Bazel Keycloak"
      run: bazelisk build src/keycloak/... --build_tag_filters=-docs-package,-release-package
    - name: "Build: Bazel Icons"
      run: bazelisk build src/icons/... --build_tag_filters=-docs-package,-release-package
    - name: "Build: Bazel Maps"
      run: bazelisk build src/maps/... --build_tag_filters=-docs-package,-release-package
    - name: "Build: Bazel Business"
      run: bazelisk build src/business/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/accordion/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/autocomplete/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/badge/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/breadcrumb/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/button/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/captcha/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/checkbox/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/checkbox-panel/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/datepicker/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/dropdown/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/field/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/file-selector/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/ghettobox/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/input/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/lightbox/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/links/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/loading/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/notification/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/option/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/pagination/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/processflow/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/radio-button/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/radio-button-panel/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/search/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/select/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/table/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/tabs/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/tag/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/textarea/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/textexpand/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/tooltip/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/usermenu/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/time-input/... --build_tag_filters=-docs-package,-release-package
    - run: bazelisk build src/public/toggle/... --build_tag_filters=-docs-package,-release-package
    - name: "Build: Bazel Public"
      run: bazelisk build src/public/... --build_tag_filters=-docs-package,-release-package

    - name: "Build: Bazel Showcase"
      run: bazelisk build src/showcase/... --build_tag_filters=-docs-package,-release-package

    - name: "Test: Run local tests"
      run: bazelisk test src/... --build_tag_filters=-e2e --test_tag_filters=-e2e --build_tests_only

    - name: "Lint: Run tslint"
      run: yarn tslint