name: Continuous Integration
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '**'
env:
  BAZEL_COMMAND: bazelisk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Copy bazel.rc to user home
      run: cp ./.github/.bazelrc ~/
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: "Yarn: Get cache directory path"
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: "Yarn: Create hash key"
      id: yarn-cache-key-name
      run: echo "::set-output name=yarn_cache_key::$(yarn -s hash yarn.lock tools/postinstall/apply-patches.js)"
    - name: "Yarn: Restore dependencies from cache"
      uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ steps.yarn-cache-key-name.outputs.yarn_cache_key }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: "Yarn: Install dependencies"
      run: yarn install --frozen-lockfile --non-interactive

    - name: "Bazelisk: Sync"
      run: bazelisk sync
    - name: "Bazelisk: Get artifacts cache directory path"
      id: bazelisk-cache-dir-path
      run: echo "::set-output name=dir::$(bazelisk info bazel-bin)"
    - name: "Bazelisk: Create hash key"
      id: bazelisk-cache-key-name
      run: echo "::set-output name=bazelisk_cache_key::$(yarn -s hash WORKSPACE .bazelversion yarn.lock)"
    - name: "Bazelisk: Restore from cache"
      uses: actions/cache@v1
      id: bazelisk-cache
      with:
        path: ${{ steps.bazelisk-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-bazelisk-build-artifacts-${{ steps.bazelisk-cache-key-name.outputs.bazelisk_cache_key }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-bazelisk-build-artifacts-${{ steps.bazelisk-cache-key-name.outputs.bazelisk_cache_key }}-

    - name: "Build: Bazel core"
      run: bazelisk build src/angular-core/... --build_tag_filters=-release-package,-prod-showcase
    - run: df -h
    - name: "Build: Bazel keycloak"
      run: bazelisk build src/angular-keycloak/... --build_tag_filters=-release-package,-prod-showcase
    - run: df -h
    - name: "Build: Bazel icons"
      run: bazelisk build src/angular-icons/... --build_tag_filters=-release-package,-prod-showcase
    - run: df -h
    - name: "Build: Bazel maps"
      run: bazelisk build src/angular-maps/... --build_tag_filters=-release-package,-prod-showcase
    - run: df -h
    - name: "Build: Bazel business"
      run: bazelisk build src/angular-business/... --build_tag_filters=-release-package,-prod-showcase
    - run: df -h
      
    - run: bazelisk build src/angular-public/loading/...
    - run: df -h
    - run: bazelisk build src/angular-public/notification/...
    - run: df -h
    - run: bazelisk build src/angular-public/option/...
    - run: df -h
    - run: bazelisk build src/angular-public/pagination/...
    - run: df -h
    - run: bazelisk build src/angular-public/processflow/...
    - run: df -h
    - run: bazelisk build src/angular-public/radio-button/...
    - run: df -h
    - run: bazelisk build src/angular-public/radio-button-panel/...
    - run: df -h
    - run: bazelisk build src/angular-public/schematics/...
    - run: df -h
    - run: bazelisk build src/angular-public/search/...
    - run: df -h
    - run: bazelisk build src/angular-public/select/...
    - run: df -h
    - run: bazelisk build src/angular-public/table/...
    - run: df -h
    - run: bazelisk build src/angular-public/tabs/...
    - run: df -h
    - run: bazelisk build src/angular-public/tag/...
    - run: df -h
    - run: bazelisk build src/angular-public/textarea/...
    - run: df -h
    - run: bazelisk build src/angular-public/textexpand/...
    - run: df -h
    - run: bazelisk build src/angular-public/time-input/...
    - run: df -h
    - run: bazelisk build src/angular-public/toggle/...
    - run: df -h
    - run: bazelisk build src/angular-public/tooltip/...
    - run: df -h
    - run: bazelisk build src/angular-public/usermenu/...
    - run: df -h
    - run: bazelisk build src/angular-public/accordion/...
    - run: df -h     
    - run: bazelisk build src/angular-public/autocomplete/...
    - run: df -h  
    - run: bazelisk build src/angular-public/badge/...
    - run: df -h
    - run: bazelisk build src/angular-public/breadcrumb/...
    - run: df -h    
    - run: bazelisk build src/angular-public/button/...
    - run: df -h        
    - run: bazelisk build src/angular-public/captcha/...
    - run: df -h       
    - run: bazelisk build src/angular-public/checkbox/...
    - run: df -h      
    - run: bazelisk build src/angular-public/checkbox-panel/...
    - run: df -h
    - run: bazelisk build src/angular-public/datepicker/...
    - run: df -h    
    - run: bazelisk build src/angular-public/dropdown/...
    - run: df -h      
    - run: bazelisk build src/angular-public/field/...
    - run: df -h
    - run: bazelisk build src/angular-public/file-selector/...
    - run: df -h 
    - run: bazelisk build src/angular-public/ghettobox/...
    - run: df -h     
    - run: bazelisk build src/angular-public/input/...
    - run: df -h
    - run: bazelisk build src/angular-public/lightbox/...
    - run: df -h
    - run: bazelisk build src/angular-public/links/...
    - run: df -h

    - name: "Build: Bazel public"
      run: bazelisk build src/angular-public/... --build_tag_filters=-release-package,-prod-showcase
    - run: df -h
    - name: "Build: Bazel showcase"
      run: bazelisk build src/showcase/... --build_tag_filters=-release-package,-prod-showcase
    - run: df -h
            
    - name: "Test: Run local tests"
      run: bazelisk test src/... --build_tag_filters=-e2e --test_tag_filters=-e2e --build_tests_only

    - name: "Lint: Run tslint"
      run: yarn tslint

  packages:
    runs-on: ubuntu-latest
    steps:
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Copy bazel.rc to user home
      run: cp ./.github/.bazelrc ~/
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: "Yarn: Get cache directory path"
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: "Yarn: Create hash key"
      id: yarn-cache-key-name
      run: echo "::set-output name=yarn_cache_key::$(yarn -s hash yarn.lock tools/postinstall/apply-patches.js)"
    - name: "Yarn: Restore dependencies from cache"
      uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ steps.yarn-cache-key-name.outputs.yarn_cache_key }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: "Yarn: Install dependencies"
      run: yarn install --frozen-lockfile --non-interactive

    - name: "Bazelisk: Sync"
      run: bazelisk sync
    - name: "Bazelisk: Get artifacts cache directory path"
      id: bazelisk-cache-dir-path
      run: echo "::set-output name=dir::$(bazelisk info bazel-bin)"
    - name: "Bazelisk: Create hash key"
      id: bazelisk-cache-key-name
      run: echo "::set-output name=bazelisk_cache_key::$(yarn -s hash WORKSPACE .bazelversion yarn.lock)"
    - name: "Bazelisk: Restore from cache"
      uses: actions/cache@v1
      id: bazelisk-cache
      with:
        path: ${{ steps.bazelisk-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-bazelisk-packages-artifacts-${{ steps.bazelisk-cache-key-name.outputs.bazelisk_cache_key }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-bazelisk-packages-artifacts-${{ steps.bazelisk-cache-key-name.outputs.bazelisk_cache_key }}-

    - name: "Build: Packages"
      run: yarn -s build

  showcase:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Copy bazel.rc to user home
      run: cp ./.github/.bazelrc ~/
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: "Yarn: Get cache directory path"
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: "Yarn: Create hash key"
      id: yarn-cache-key-name
      run: echo "::set-output name=yarn_cache_key::$(yarn -s hash yarn.lock tools/postinstall/apply-patches.js)"
    - name: "Yarn: Restore dependencies from cache"
      uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ steps.yarn-cache-key-name.outputs.yarn_cache_key }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: "Yarn: Install dependencies"
      run: yarn install --frozen-lockfile --non-interactive

    - name: "Bazelisk: Sync"
      run: bazelisk sync
    - name: "Bazelisk: Get artifacts cache directory path"
      id: bazelisk-cache-dir-path
      run: echo "::set-output name=dir::$(bazelisk info bazel-bin)"
    - name: "Bazelisk: Create hash key"
      id: bazelisk-cache-key-name
      run: echo "::set-output name=bazelisk_cache_key::$(yarn -s hash WORKSPACE .bazelversion yarn.lock)"
    - name: "Bazelisk: Restore from cache"
      uses: actions/cache@v1
      id: bazelisk-cache
      with:
        path: ${{ steps.bazelisk-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-bazelisk-showcase-artifacts-${{ steps.bazelisk-cache-key-name.outputs.bazelisk_cache_key }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-bazelisk-showcase-artifacts-${{ steps.bazelisk-cache-key-name.outputs.bazelisk_cache_key }}-

    - name: "Build: Showcase"
      run: yarn -s build:showcase
    - name: "Pack: Showcase"
      run: mv $(npm pack ./dist/releases/showcase | tail -n 1) sbb-esta-angular-showcase.tgz
    - name: "Deploy: Staging"
      run: |
        curl --url https://angular-staging.app.sbb.ch/$PR_NUMBER \
        -X POST --user sbb:ezUxDHgb6rAHTDU0HLHJ \
        -F "tarball=@sbb-esta-angular-showcase.tgz"